# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the turtlebrowser/5.15.2 branch
  push:
    branches: [ turtlebrowser/5.15.2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: JFrog

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Add conan jfrog remote
        run: conan remote add jfrog https://turtlebrowser.jfrog.io/artifactory/api/conan/conan

      - name: Authenticate with jfrog
        run: conan user -p ${{ secrets.JFROG_PASSWORD }} -r jfrog ${{ secrets.JFROG_USER }}

      - name: Install conan-qt locally
        run: conan export . qt/5.15.2@turtlebrowser/test

      - name: Upload the Qt recipe to jfrog
        run: conan upload qt/5.15.2@turtlebrowser/test --confirm -r jfrog
        
