name: Publish Qt recipe to JFrog

on:
  push:
    branches: [ turtlebrowser/5.15.2 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: JFrog

    steps:
      - uses: actions/checkout@v2

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Add conan jfrog remote
        run: conan remote add jfrog https://turtlebrowser.jfrog.io/artifactory/api/conan/conan

      - name: Authenticate with jfrog
        run: conan user -p ${{ secrets.JFROG_PASSWORD }} -r jfrog ${{ secrets.JFROG_USER }}

      - name: Install conan-qt locally
        run: conan export . qt/5.15.2@turtlebrowser/test

      - name: Upload the Qt recipe to jfrog
        run: conan upload qt/5.15.2@turtlebrowser/test --confirm -r jfrog
